name: Build Linux Release AppImage

on:
  push:
    branches:
      - ci-test
    # tags:
    #   - 'v*'        # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-22.04  # glibc 2.35

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          cmake \
          wget \
          unzip \
          libgl1-mesa-dev \
          libglu1-mesa-dev

    - name: Install Qt 6.10
      run: |
        wget https://download.qt.io/official_releases/qt/6.10/6.10.0/qt-opensource-linux-x64-6.10.0.run
        chmod +x qt-opensource-linux-x64-6.10.0.run
        # Use non-interactive installer script to install Qt
        ./qt-opensource-linux-x64-6.10.0.run --platform minimal --script install-qt.qs
        echo "Qt installed at $HOME/Qt/6.10.0/gcc_64"
        echo "CMAKE_PREFIX_PATH=$HOME/Qt/6.10.0/gcc_64/lib/cmake" >> $GITHUB_ENV

    - name: Setup Build Directory
      run: |
        mkdir -p build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=release \
          -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH
        cmake --build . --parallel
        cmake --install . --prefix release

    - name: Download linuxdeployqt
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage

    - name: Build AppImage
      run: |
        cd build/release/bin
        ../../linuxdeployqt-continuous-x86_64.AppImage \
          appQtServiceLab \
          -qmldir=../qml \
          -bundle-non-qt-libs \
          -appimage
    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: QtServiceLab-AppImage
        path: build/release/bin/*.AppImage
