name: Build Linux Release AppImage

on:
  push:
    branches:
      - ci-test
  workflow_dispatch:

env:
  CI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          cmake \
          wget \
          unzip \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxcb-xinerama0-dev \
          libxkbcommon-dev \
          libvulkan-dev \
          ca-certificates \
          xz-utils

    - name: Download and install Qt 6.10.8
      run: |
        wget https://download.qt.io/official_releases/qt/6.10/6.10.8/qt-opensource-linux-x64-6.10.8.run
        chmod +x qt-opensource-linux-x64-6.10.8.run
        ./qt-opensource-linux-x64-6.10.8.run --script qt-install.qs
        echo "$HOME/Qt/6.10.8/gcc_64/bin" >> $GITHUB_PATH

    - name: Verify qmake
      run: qmake -v

    - name: Setup Build Directory
      run: |
        mkdir -p build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=release
        cmake --build . --parallel
        cmake --install . --prefix release

    - name: Download linuxdeployqt
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous
