name: Build Linux Release AppImage

on:
  push:
    branches:
      - ci-test
    # tags:
    #   - 'v*'        # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-22.04  # glibc 2.35

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake wget unzip qt6-base-dev qt6-declarative-dev qt6-quickcontrols2-dev

    - name: Setup Build Directory
      run: |
        mkdir -p build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=release
        cmake --build . --parallel
        cmake --install . --prefix release

    - name: Download linuxdeployqt
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage

    - name: Build AppImage
      run: |
        cd build/release/bin
        ../../linuxdeployqt-continuous-x86_64.AppImage \
          appQtServiceLab \
          -qmldir=../qml \
          -bundle-non-qt-libs \
          -appimage

    - name: Upload AppImage
      uses: actions/upload-artifact@v3
      with:
        name: QtServiceLab-AppImage
        path: build/release/bin/*.AppImage
